# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/alert/instance_down.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # Prometheus
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  # Storage
  - job_name: 'victoria-metrics'
    static_configs:
    - targets: ['victoria-metrics:8428']

  # Node
  - job_name: 'flask-exporter'
    static_configs:
    - targets: ['flask-exporter:9201']

  - job_name: 'airflow-exporter'
    static_configs:
    - targets: ['airflow-exporter:5050']
    metrics_path: /admin/metrics

  - job_name: 'mysql-exporter'
    static_configs:
    - targets: ['mysql-exporter:9104']

  - job_name: 'django-exporter'
    static_configs:
    - targets: ['django-exporter']
    metrics_path: /prometheus/metrics

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9200']

  # Faderate (GCE)
  # - job_name: 'federate'
  #   scrape_interval: 15s
  #   honor_labels: true
  #   metrics_path: '/federate'
  #   params:
  #     'match[]':
  #       - '{job=~"prometheus.*"}'
  #       - '{job="node_exporter"}'
  #       - '{job="flask_exporter"}'
  #       - '{job="mysql_exporter"}'
  #       - '{job="mongodb_exporter"}'
  #   static_configs:
  #     - targets:
  #       
  


# Remote Storage
remote_write:
  - url: http://victoria-metrics:8428/api/v1/write